// SPDX-License-Identifier: Apache-2.0 OR MIT

#![cfg(nightly)]
#![no_core]
#![feature(no_core)]

// Make sure the items generated by pin-project don't depend on paths like
// `core`, `core::prelude::*`, etc.
//
// Note:
// - pin-project depends on core's items and is not really usable
//   in a no-core environment.
// - If the procedural macro crate does not have its own items, it may be
//   preferable not to support this for compatibility with reexport.

extern crate core as _core;

// Dummy module to check that the expansion refers to the crate.
mod pin_project {}

// This works in 2018 edition, but in 2015 edition it gives an error:
// ```text
// error[E0659]: `pin` is ambiguous (derive helper attribute vs any other name)
//  --> tests/rust-2015/../include/basic-safe-part.rs:3:1
//   |
// 3 | #[pin_project]
//   | ^^^^^^^^^^^^^^ ambiguous name
//   |
// ```
#[allow(unused_imports)]
use ::pin_project as pin;

pub mod module {
    use _core::{fmt::Debug, include, prelude::v1::derive};

    include!("../include/basic.rs");
}

use _core::{fmt::Debug, include, prelude::v1::derive};

include!("../include/basic.rs");
