jobs:
- job: ${{ parameters.name }}
  displayName: Rustdoc
  pool:
    vmImage: ubuntu-16.04

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust: ${{ parameters.rust }}

    - script: RUSTDOCFLAGS=-Dwarnings cargo doc --no-deps --all --all-features
      displayName: cargo doc --all-features
