name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * 5'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@04a42ca09aaeb9b6c0bce43c23fb9e13eb197d85 # 2026.9.9
    permissions:
      security-events: write # for github/codeql-action/*
    with:
      implicit_provenance_casts: false # we cast ptr to int to move check in test (addr requires Rust 1.84)
  test:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-test.yml@04a42ca09aaeb9b6c0bce43c23fb9e13eb197d85 # 2026.9.9
    with:
      rust: 1.71,stable,beta,nightly
      additional-no-std-crates: tests/no-std,tests/rust-2015
      miri-args: --exclude no-core
