name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@6bdbb973f58616e14d2905249e163a0ac857ef24 # main
    permissions:
      security-events: write # for github/codeql-action/*
  miri:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-miri.yml@6bdbb973f58616e14d2905249e163a0ac857ef24 # main
  msrv:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-msrv.yml@6bdbb973f58616e14d2905249e163a0ac857ef24 # main
  test:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-test.yml@6bdbb973f58616e14d2905249e163a0ac857ef24 # main
    with:
      rust: 1.71,stable,beta,nightly
      additional-no-std-crates: tests/no-std,tests/rust-2015
