name: Release

permissions: {}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be increased
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    if: github.repository_owner == 'taiki-e'
    uses: taiki-e/github-actions/.github/workflows/rust-release.yml@1bb80ca038216cd1fb7b6ca6d76240b3772963ab # main
    permissions:
      contents: write # for taiki-e/create-gh-release-action
      id-token: write # for rust-lang/crates-io-auth-action
      attestations: write # unused (used when options for uploading binaries are set)
    secrets:
      PUSH_TOKEN_APP_CLIENT_ID: ${{ secrets.PUSH_TOKEN_APP_CLIENT_ID }}
      PUSH_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PUSH_TOKEN_APP_PRIVATE_KEY }}
    with:
      version: ${{ inputs.version }}
      package: pin-project,pin-project-internal
